### ISSUE TITLE
Core 0 panic'ed (LoadProhibited)

### ISSUE THREAD

**Issue by Harvie** [mongoose-os-libs/mqtt#15]
Hello,
i am getting this error from MQTT module. Can you please take a look at it?

![image](https://user-images.githubusercontent.com/276504/72892681-6c601600-3d17-11ea-977e-09f23844ab3a.png)

![image](https://user-images.githubusercontent.com/276504/72892649-5a7e7300-3d17-11ea-902b-fa79e06626bb.png)

**Comment by rojer** [comment]
MQTT had a big refactoring, this is a regression.
thanks for reporting, change is on the way!

**Comment by Harvie** [comment]
>  rojer closed this in 998dcb9 7 minutes ago

Thanks for swift response! What i need to do to integrate this fix to my project? Is doing `build --clean` enough to pull the fixed version or do i have to wait for official release?

**Comment by rojer** [comment]
when your project uses mos-latest, as your evidently does, it will pull libraries every hour.
you can force it by deleting deps/mqtt, so it will clone the repo.

**Comment by Harvie** [comment]
Aha. That is the problem. We should have used stable version in the first place.
Switched to stable version by `mos update release` command. It will probably save us from similar problems in futue. Thanks.

**Comment by rojer** [comment]
yep. but i do encourage you to test with -latest as well, otherwise bugs not found in latest will bite you in release, only a bit later :)
