### ISSUE TITLE
2.17 is eating messages

### ISSUE THREAD

**Issue by pimvanpelt** [mongoose-os-libs/mqtt#18]
When upgrading from 2.16.0 to 2.17.0, the library (after its multi-mqtt refactor) started eating publication messages at qos 0, 1 and 2.

Minimal repro:
```
static void mqtt_connect(
    struct mg_connection *nc, const char *client_id,
    struct mg_send_mqtt_handshake_opts *opts, void *fn_arg) {
  char topic[100];
  char payload[100];
  snprintf(topic, sizeof(topic), "%s/stat", mgos_sys_config_get_device_id());
  snprintf(payload, sizeof(payload), "offline");
  LOG(LL_DEBUG, ("Setting will topic='%s' payload='%s', for when we disconnect",
                 topic, payload));
  opts->will_topic = strdup(topic);
  opts->will_message = strdup(payload);
  opts->flags |= MG_MQTT_WILL_RETAIN;
  mg_send_mqtt_handshake_opt(nc, client_id, *opts);
  (void) fn_arg;
}
mgos_mqtt_set_connect_fn(mqtt_connect, NULL);
```

***Expected***: will topic is set and received upon connect success.

The behavior in 2.16.0 is correct:
`esp8266_24538D/stat offline`

***Actual***: the will topic is never sent.
The behavior in 2.17 is erratic:
(no will topic is seen).

**Comment by pimvanpelt** [comment]
Another example showing 2.17.0 has a regression:

```
static void mqtt_ev(struct mg_connection *nc, int ev,
                                       void *ev_data, void *user_data) {
  switch (ev) {
    case MG_EV_MQTT_CONNACK: {
      char topic[100];
      snprintf(topic, sizeof(topic), "%s/stat",
               mgos_sys_config_get_device_id());
      mgos_mqtt_pub((char *) topic, "online", 6, 0, true);
      break;
    }
  }            
  (void) nc;     
  (void) ev_data;
  (void) user_data;
}
mgos_mqtt_add_global_handler(mqtt_ev, NULL);
```

***Expected***: the 'online' pub is sent upon connection ack.

The behavior in 2.16.0 is correct:
`esp8266_24538D/stat online`

***Actual***: the 'online' pub is never sent.
The behavior in 2.17 is erratic.
(no online topic is seen).

**Comment by pimvanpelt** [comment]
Confirmed that the application works in Mongoose OS 2.17.0 when pinning mqtt to 2.16.0 in `mos.yml`.

**Comment by rojer** [comment]
can you post level 3 log? it should show relevant MQTT events.

**Comment by pimvanpelt** [comment]
Logs for 2.16.0 -- https://paste.ubuntu.com/p/nhFMVQVD7x/
Logs for 2.17.0 -- https://paste.ubuntu.com/p/Y7yCYgMNsk/

**Comment by pimvanpelt** [comment]
Practical repro, using a nodemcu v3 (with LED on gpio2 and button on gpio0).
 
Based on `empty` app, with `homeassistant` in `mos.yml`:
src/main.c:
```
#include "mgos.h"
#include "mgos_config.h"
#include "mgos_homeassistant.h"

enum mgos_app_init_result mgos_app_init(void) {
  mgos_homeassistant_fromfile(mgos_homeassistant_get_global(), 
    mgos_sys_config_get_homeassistant_config());
  return MGOS_APP_INIT_SUCCESS;
}
```

fs/ha.conf:
```
{
   "provider" : {
      "gpio" : [
         {
            "momentary" : true,
            "type" : "binary_sensor",
            "gpio" : 0,
            "name" : "button",
            "inverted" : true,
            "debounce" : 50
         },
         {
            "inverted" : true,
            "type" : "switch",
            "name" : "LED",
            "gpio" : 2
         }
      ]
   }
}
```

**Comment by rojer** [comment]
pushed a fix. we were not declaring connection "clear for sending" soon enough when we should have.
also, qos 0 messages should completely bypass the queue since nothing is guaranteed about their ordering anyway.

**Comment by pimvanpelt** [comment]
Confirmed that latest fixes the regression on `ubuntu` and `esp8266` platform. Thanks, @rojer ++
