### ISSUE TITLE
Corrupted data via MQTT.pub

### ISSUE THREAD

**Issue by rmasarovic** [mongoose-os-libs/mqtt#2]
i use ESP8266 library MQTT with google iot core but problem is device send all prints stream. I have on cloud all this. getInfo() + "Publikovane"; Somebody now reason why device send all prints on this method? Device really send all device log via MQTT.pub. I find on cloud data for example this 
esp8266-dht22 43 1509271334.818 2|mgos_fs_put_handler  Appended 512 bytes to init.js
esp8266-dht22 44 1509271335.320 2|mgos_fs_put_handler  Appended 512 bytes to init.js
esp8266-dht22 45 1509271335.823 2|mgos_fs_put_handler  Appended 512 bytes to init.js
esp8266-dht22 46 1509271336.389 2|mgos_fs_put_handler  Appended 512 bytes to init.js
esp8266-dht22 47 1509271336.896 2|mgos_fs_put_handler  Appended 512 bytes to init.js
esp8266-dht22 48 1509271337.376 2|mgos_fs_put_handler  Appended 470 bytes to init.js
esp8266-dht22 49 1509271337.671 2|mgos_system_restart_ Rebooting in 100 ms

iam trying use MTQQ with google iot core on esp8266 nodemcu with mongoose i have correct set key, projects
device correct connect to google mtqq and publish message. DEVICE => GOOGLE IOT => PUBSUB=>GOOGLE DATAFLOW=>CLOUD FILE but i have corrupted messages and i dont know why because i send only "MY MESSAGE" but in google cloud file i find device logs in cloud file. Its like print stream go to mtqq.pub(message) or i dont know. i dont send only "MY MESSAGE". For same reason everything on print() go with mtqq.pub send to cloud. i want send only "MY MESSAGE" 

Here is code: 

load('api_config.js');
load('api_gpio.js');
load('api_mqtt.js');
load('api_net.js');
load('api_sys.js');
// Load Mongoose OS API
load('api_timer.js');
load('api_dht.js');
//let led = Cfg.get('pins.led');
let led = 0;
let button = Cfg.get('pins.button');
let topic = '/devices/' + Cfg.get('device.id') + '/events';

// GPIO pin which has a DHT sensor data wire connected
let pin = 5;
// Initialize DHT library
let dht = DHT.create(pin, DHT.DHT22);
let isConnected = false;
// print('LED GPIO:', led, 'button GPIO:', button);
let getInfo = function() {
  return JSON.stringify({
    ts: Sys.uptime(),
    total_ram: Sys.total_ram(),
    free_ram: Sys.free_ram()
  });
};
Timer.set(
  60 * 1000,
  true,
  function(){
    if(isConnected){
      publishData();
    }
  },null
);

Net.setStatusEventHandler(function(ev, arg) {
  let evs = '???';
  if (ev === Net.STATUS_DISCONNECTED) {
    evs = 'DISCONNECTED';
  } else if (ev === Net.STATUS_CONNECTING) {
    evs = 'CONNECTING';
  } else if (ev === Net.STATUS_CONNECTED) {
    evs = 'CONNECTED';
  } else if (ev === Net.STATUS_GOT_IP) {
    evs = 'GOT_IP';
  }
  print('== Net event:', ev, evs);
}, null);
MQTT.setEventHandler(function(conn, ev){
  if (ev === MQTT.EV_CONNACK){
    print('CONNECTED');
    isConnected = true;
    publishData();
  }
}, null);
function publishData(){
  let ok = MQTT.pub(topic, getInfo());
  if(ok){
    print('Publikovane');
  }
  else{
    print('Chyba publikovania');
  }
}

**Comment by christianmue1980a** [comment]
I observe the same issue - everything which is logged by print(..) is published to MQTT

**Comment by rojer** [comment]
too old, please reopen if it's still relevant.
