### ISSUE TITLE
Last Will Retained Message

### ISSUE THREAD

**Issue by engwan** [mongoose-os-libs/mqtt#4]
Is there currently any way to set the Last Will message to be retained?

Thanks

**Comment by cpq** [comment]
Not currently.
Patch the library.

1. Add a config section `mqtt.will_retain`, false by default.
2.  Add a snippet similar to https://github.com/mongoose-os-libs/mqtt/blob/master/src/mgos_mqtt.c#L128-L130 , check if `mqtt.will_retain` is true, then set the flag `MG_MQTT_WILL_RETAIN` (see https://github.com/cesanta/dev/blob/master/mongoose/src/mqtt.h#L112)

Rebuild your app using a local build (`mos build --local ...)`

If that works out fine, send a PR
